const Sobremesas = [
    {
      id: 1,
      nome: 'Bolo de Chocolate',
      porcao: '8 porções',
      tempoPreparo: '60 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Farinha de trigo', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Cacau em pó', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Ovos', quantidade: '2 unidades', valor: 2.0 },
        { nome: 'Leite', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Fermento em pó', quantidade: '1 colher de chá', valor: 1.0 },
      ],
    },
    {
      id: 2,
      nome: 'Torta de Limão',
      porcao: '8 porções',
      tempoPreparo: '45 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Biscoitos de maisena', quantidade: '200g', valor: 2.5 },
        { nome: 'Manteiga derretida', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Leite condensado', quantidade: '1 lata', valor: 3.0 },
        { nome: 'Suco de limão', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Creme de leite', quantidade: '1 lata', valor: 3.0 },
      ],
    },
    {
      id: 3,
      nome: 'Cheesecake de Morango',
      porcao: '8 porções',
      tempoPreparo: '60 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Biscoitos de Graham', quantidade: '200g', valor: 2.5 },
        { nome: 'Manteiga derretida', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Cream cheese', quantidade: '400g', valor: 4.0 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Ovos', quantidade: '3 unidades', valor: 3.0 },
        { nome: 'Essência de baunilha', quantidade: '1 colher de chá', valor: 1.0 },
        { nome: 'Geleia de morango', quantidade: '1/2 xícara', valor: 2.0 },
      ],
    },
    {
      id: 4,
      nome: 'Pudim de Leite',
      porcao: '8 porções',
      tempoPreparo: '50 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Leite condensado', quantidade: '1 lata', valor: 3.0 },
        { nome: 'Leite', quantidade: '2 latas (use a lata de leite condensado como medida)', valor: 3.0 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Ovos', quantidade: '4 unidades', valor: 4.0 },
        { nome: 'Essência de baunilha', quantidade: '1 colher de chá', valor: 1.0 },
      ],
    },
    {
      id: 5,
      nome: 'Bolo de Morango',
      porcao: '8 porções',
      tempoPreparo: '60 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Farinha de trigo', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Morangos', quantidade: '200g', valor: 3.0 },
        { nome: 'Ovos', quantidade: '2 unidades', valor: 2.0 },
        { nome: 'Leite', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Fermento em pó', quantidade: '1 colher de chá', valor: 1.0 },
      ],
    },
    {
      id: 6,
      nome: 'Sorvete de Baunilha',
      porcao: '4 porções',
      tempoPreparo: '30 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Creme de leite', quantidade: '1 lata', valor: 3.0 },
        { nome: 'Leite condensado', quantidade: '1 lata', valor: 3.0 },
        { nome: 'Essência de baunilha', quantidade: '1 colher de chá', valor: 1.0 },
      ],
    },
    {
      id: 7,
      nome: 'Tiramisu',
      porcao: '8 porções',
      tempoPreparo: '45 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Queijo mascarpone', quantidade: '250g', valor: 4.0 },
        { nome: 'Ovos', quantidade: '2 unidades', valor: 2.0 },
        { nome: 'Açúcar', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Café forte', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Biscoitos de champanhe', quantidade: '200g', valor: 2.5 },
        { nome: 'Cacau em pó', quantidade: '2 colheres de sopa', valor: 2.0 },
      ],
    },
    {
      id: 8,
      nome: 'Bolo de Cenoura',
      porcao: '8 porções',
      tempoPreparo: '50 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Cenouras', quantidade: '3 unidades', valor: 2.5 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Óleo', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Ovos', quantidade: '3 unidades', valor: 3.0 },
        { nome: 'Farinha de trigo', quantidade: '2 xícaras', valor: 2.0 },
        { nome: 'Fermento em pó', quantidade: '1 colher de sopa', valor: 1.0 },
      ],
    },
    {
      id: 9,
      nome: 'Pavê de Chocolate',
      porcao: '8 porções',
      tempoPreparo: '40 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Biscoitos de maisena', quantidade: '200g', valor: 2.5 },
        { nome: 'Leite condensado', quantidade: '1 lata', valor: 3.0 },
        { nome: 'Leite', quantidade: '2 latas (use a lata de leite condensado como medida)', valor: 3.0 },
        { nome: 'Cacau em pó', quantidade: '3 colheres de sopa', valor: 2.0 },
        { nome: 'Amido de milho', quantidade: '2 colheres de sopa', valor: 1.0 },
        { nome: 'Chocolate meio amargo', quantidade: '150g', valor: 3.0 },
      ],
    },
    {
      id: 10,
      nome: 'Torta de Chocolate',
      porcao: '8 porções',
      tempoPreparo: '50 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Biscoitos de chocolate', quantidade: '200g', valor: 2.5 },
        { nome: 'Manteiga derretida', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Chocolate meio amargo', quantidade: '200g', valor: 4.0 },
        { nome: 'Creme de leite', quantidade: '1 lata', valor: 3.0 },
      ],
    },
    {
      id: 11,
      nome: 'Bolo de Morango com Chantilly',
      porcao: '8 porções',
      tempoPreparo: '60 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Farinha de trigo', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Morangos', quantidade: '200g', valor: 3.0 },
        { nome: 'Ovos', quantidade: '2 unidades', valor: 2.0 },
        { nome: 'Leite', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Fermento em pó', quantidade: '1 colher de chá', valor: 1.0 },
        { nome: 'Chantilly', quantidade: '1 xícara', valor: 3.0 },
      ],
    },
    {
      id: 12,
      nome: 'Creme Brûlée',
      porcao: '4 porções',
      tempoPreparo: '60 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Creme de leite', quantidade: '1 xícara', valor: 3.0 },
        { nome: 'Açúcar', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Gemas de ovo', quantidade: '4 unidades', valor: 4.0 },
        { nome: 'Essência de baunilha', quantidade: '1 colher de chá', valor: 1.0 },
      ],
    },
    {
      id: 13,
      nome: 'Bolo de Coco',
      porcao: '8 porções',
      tempoPreparo: '50 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Farinha de trigo', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Coco ralado', quantidade: '1 xícara', valor: 2.5 },
        { nome: 'Ovos', quantidade: '2 unidades', valor: 2.0 },
        { nome: 'Leite de coco', quantidade: '1 xícara', valor: 2.5 },
        { nome: 'Fermento em pó', quantidade: '1 colher de chá', valor: 1.0 },
      ],
    },
    {
      id: 14,
      nome: 'Pavê de Morango',
      porcao: '8 porções',
      tempoPreparo: '45 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Biscoitos de maisena', quantidade: '200g', valor: 2.5 },
        { nome: 'Leite condensado', quantidade: '1 lata', valor: 3.0 },
        { nome: 'Leite', quantidade: '2 latas (use a lata de leite condensado como medida)', valor: 3.0 },
        { nome: 'Morangos', quantidade: '200g', valor: 3.0 },
      ],
    },
    {
      id: 15,
      nome: 'Torta de Maçã',
      porcao: '8 porções',
      tempoPreparo: '50 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Maçãs', quantidade: '4 unidades', valor: 2.0 },
        { nome: 'Açúcar', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Canela em pó', quantidade: '1 colher de chá', valor: 1.0 },
        { nome: 'Farinha de trigo', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Manteiga derretida', quantidade: '1/2 xícara', valor: 2.0 },
      ],
    },
    {
      id: 16,
      nome: 'Brigadeiro',
      porcao: '20 unidades',
      tempoPreparo: '30 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Leite condensado', quantidade: '1 lata', valor: 3.0 },
        { nome: 'Chocolate em pó', quantidade: '4 colheres de sopa', valor: 2.0 },
        { nome: 'Manteiga', quantidade: '2 colheres de sopa', valor: 2.0 },
        { nome: 'Granulado', quantidade: '100g', valor: 2.5 },
      ],
    },
    {
      id: 17,
      nome: 'Pudim de Chocolate',
      porcao: '8 porções',
      tempoPreparo: '50 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Leite condensado', quantidade: '1 lata', valor: 3.0 },
        { nome: 'Leite', quantidade: '2 latas (use a lata de leite condensado como medida)', valor: 3.0 },
        { nome: 'Chocolate em pó', quantidade: '4 colheres de sopa', valor: 2.0 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Ovos', quantidade: '4 unidades', valor: 4.0 },
      ],
    },
    {
      id: 18,
      nome: 'Cupcake de Baunilha',
      porcao: '12 unidades',
      tempoPreparo: '40 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Farinha de trigo', quantidade: '2 xícaras', valor: 2.5 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Leite', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Manteiga derretida', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Ovos', quantidade: '2 unidades', valor: 2.0 },
        { nome: 'Essência de baunilha', quantidade: '1 colher de chá', valor: 1.0 },
        { nome: 'Fermento em pó', quantidade: '1 colher de chá', valor: 1.0 },
      ],
    },
    {
      id: 19,
      nome: 'Sorvete de Morango',
      porcao: '4 porções',
      tempoPreparo: '30 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Morangos', quantidade: '200g', valor: 3.0 },
        { nome: 'Açúcar', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Creme de leite', quantidade: '1 lata', valor: 3.0 },
      ],
    },
    {
      id: 20,
      nome: 'Bolo de Fubá',
      porcao: '8 porções',
      tempoPreparo: '50 minutos',
      categoria: 'Sobremesas',
      ingredientes: [
        { nome: 'Fubá', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Açúcar', quantidade: '1 xícara', valor: 2.0 },
        { nome: 'Leite', quantidade: '2 xícaras', valor: 2.0 },
        { nome: 'Óleo', quantidade: '1/2 xícara', valor: 2.0 },
        { nome: 'Ovos', quantidade: '3 unidades', valor: 3.0 },
        { nome: 'Fermento em pó', quantidade: '1 colher de sopa', valor: 1.0 },
      ],
    },
  ];
  
  export default Sobremesas;
  